<?php

namespace Mickiewicz\TadeuczBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReflectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReflectionRepository extends EntityRepository
{
}
